name: Ruby

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
      - name: Set up KinD
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.1"
      - name: In-cluster tests
        run: |
          bundle exec rake integration_test
